name: CI

on: [push]

jobs:
  build:
    name: Build

    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
